-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), ui.GENDER, COUNT(DISTINCT ui.USER_ID) as USERS
FROM ONLINE_SALE os
JOIN USER_INFO ui
on os.USER_ID = ui.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER ASC
